# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'PearToPearNetwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PearToPearNetwork
  pod 'CocoaAsyncSocket'
  pod 'DJIWidget', '~> 1.6.1'

  target 'PearToPearNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PearToPearNetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
